language: node_js
node_js: node
notifications:
  email: false
install:
  - yarn install
jobs:
  include:
    - stage: "Lint, Test and Build"
    - script: yarn lint && yarn test && yarn generate
    - stage: Deploy
      script: mkdir dist && echo "lhd.nwplus.io" >> dist/cname && yarn generate:prod
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep_history: true
        local_dir: dist
        on:
          branch: master
stages:
  - "Lint, Test and Build"
  - name: Deploy
    if: branch = master