version: '3.7'
services:
  nuxt:
    build: .
    command: yarn run dev
    working_dir: /usr/src/nuxt-app
    volumes:
      - .:/usr/src/nuxt-app
      - /usr/src/nuxt-app/node_modules
    ports:
      - "3000:3000"
    environment:
      HOST: 0.0.0.0
